# Generated by Django 4.1.7 on 2023-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vo', 'Voice Over'), ('bg_music', 'Background Music'), ('video_music', 'Video Music')], max_length=20)),
                ('high_volume', models.IntegerField()),
                ('low_volume', models.IntegerField()),
                ('video_component_id', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
        ),
    ]
